swagger: '2.0'
info:
  title: Crewmeister API
  description: Move your app forward with the Crewmeister API
  version: "2.0.0"
host: crewmeister.com
schemes:
  - https
basePath: /api/v2
produces:
  - application/json

paths:
  /crew/{crew_id}/time-tracking/stamp-chains:
    $ref: 'paths/time-tracking/stamp-chains.yaml'

  /crew/{crew_id}/time-tracking/bookings:
    $ref: 'paths/time-tracking/bookings.yaml'

  /crew/{crew_id}/time-tracking/durations:
    $ref: 'paths/time-tracking/durations.yaml'

  /crew/{crew_id}/time-tracking/stamps:
    $ref: 'paths/time-tracking/stamps.yaml'

  /prices/config:
    $ref: 'paths/payment/prices/config.yaml'

  /prices/calculate:
    $ref: 'paths/payment/prices/calculate.yaml'

definitions:
  Booking:
    $ref: 'definitions/Booking.yaml'
  Stamp:
    $ref: 'definitions/Stamp.yaml'
  Duration:
    $ref: 'definitions/Duration.yaml'
